#!/bin/bash
set -e

BLUE='\033[0;34m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; NC='\033[0m'; BOLD='\033[1m'

echo ""
echo -e "${BOLD}  EAR Labs Scraper — Powered by WeOps${NC}"
echo -e "  ${BLUE}AI-powered lead generation platform${NC}"
echo ""

if ! command -v docker &>/dev/null; then
  echo -e "  ${RED}✗ Docker not found.${NC} Install from https://docker.com/get-started"
  exit 1
fi

if [ ! -f .env ]; then
  echo -e "  ${YELLOW}No .env file found. Let's set one up — takes about 2 minutes.${NC}"
  echo ""
  echo -e "  ${BOLD}Step 1 of 3 — Required keys${NC}"
  echo -e "  ${BLUE}(The app won't start without these two)${NC}"
  echo ""

  echo -e "  Google Places API Key"
  echo -e "  ${BLUE}→ Get it: console.cloud.google.com/apis/library/places-backend.googleapis.com${NC}"
  read -p "  Paste key: " GOOGLE_PLACES_API_KEY
  echo ""

  echo -e "  Anthropic (Claude) API Key"
  echo -e "  ${BLUE}→ Get it: console.anthropic.com${NC}"
  read -p "  Paste key: " ANTHROPIC_API_KEY
  echo ""

  AUTH_SECRET_KEY=$(python3 -c "import secrets; print(secrets.token_hex(32))" 2>/dev/null || openssl rand -hex 32)

  echo -e "  ${BOLD}Step 2 of 3 — Email provider${NC}"
  echo -e "  ${BLUE}How should outreach emails be sent? (changeable later in Settings)${NC}"
  echo ""
  echo "  [1] Gmail       — send from your Google account (free, good for low volume)"
  echo "  [2] Instantly   — cold outreach at scale with warmup (recommended)"
  echo "  [3] Skip for now"
  read -p "  Choice [1/2/3]: " EMAIL_CHOICE
  echo ""

  EMAIL_PROVIDER="gmail"
  GMAIL_CLIENT_ID=""; GMAIL_CLIENT_SECRET=""; GMAIL_REFRESH_TOKEN=""
  INSTANTLY_API_KEY=""; INSTANTLY_CAMPAIGN_ID=""

  if [ "$EMAIL_CHOICE" = "1" ]; then
    EMAIL_PROVIDER="gmail"
    echo -e "  Gmail OAuth setup: ${BLUE}console.cloud.google.com/apis/library/gmail.googleapis.com${NC}"
    read -p "  Gmail Client ID: " GMAIL_CLIENT_ID
    read -p "  Gmail Client Secret: " GMAIL_CLIENT_SECRET
    read -p "  Gmail Refresh Token: " GMAIL_REFRESH_TOKEN
    echo ""
  elif [ "$EMAIL_CHOICE" = "2" ]; then
    EMAIL_PROVIDER="instantly"
    echo -e "  Instantly.ai keys: ${BLUE}app.instantly.ai/app/settings/integrations${NC}"
    read -p "  Instantly API Key: " INSTANTLY_API_KEY
    read -p "  Instantly Campaign ID: " INSTANTLY_CAMPAIGN_ID
    echo ""
  fi

  echo -e "  ${BOLD}Step 3 of 3 — Optional integrations${NC}"
  echo -e "  ${BLUE}(All of these can be added later in Settings → API Keys)${NC}"
  echo ""
  read -p "  GoHighLevel API Key        (Enter to skip): " GHL_API_KEY
  read -p "  GoHighLevel Location ID    (Enter to skip): " GHL_LOCATION_ID
  read -p "  Yelp API Key               (Enter to skip): " YELP_API_KEY
  echo ""

  cat > .env <<EOF
# EAR Labs Scraper — Generated by ./start.sh
# Update any key anytime in Settings → API Keys inside the app

GOOGLE_PLACES_API_KEY=${GOOGLE_PLACES_API_KEY}
ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
AUTH_SECRET_KEY=${AUTH_SECRET_KEY}

EMAIL_PROVIDER=${EMAIL_PROVIDER}
GMAIL_CLIENT_ID=${GMAIL_CLIENT_ID}
GMAIL_CLIENT_SECRET=${GMAIL_CLIENT_SECRET}
GMAIL_REFRESH_TOKEN=${GMAIL_REFRESH_TOKEN}
INSTANTLY_API_KEY=${INSTANTLY_API_KEY}
INSTANTLY_CAMPAIGN_ID=${INSTANTLY_CAMPAIGN_ID}

GHL_API_KEY=${GHL_API_KEY}
GHL_LOCATION_ID=${GHL_LOCATION_ID}

YELP_API_KEY=${YELP_API_KEY}

# Add these later in Settings → API Keys:
HUNTER_API_KEY=
PDL_API_KEY=
GOOGLE_SEARCH_API_KEY=
GOOGLE_SEARCH_CX=
EOF

  echo -e "  ${GREEN}✓ Setup complete — .env created${NC}"
  echo ""
fi

echo -e "  Starting EAR Labs Scraper..."
docker compose up --build -d

echo ""
echo -e "  ${GREEN}${BOLD}✓ Running!${NC}"
echo ""
echo -e "  ${BOLD}→ Open http://localhost:3000 in your browser${NC}"
echo ""
echo -e "  Sign in with your email — you'll get a 6-digit code."
echo -e "  Add remaining keys anytime: Settings → API Keys."
echo ""
echo -e "  Commands:"
echo -e "  • Stop:    docker compose down"
echo -e "  • Logs:    docker compose logs -f"
echo -e "  • Restart: docker compose restart"
echo ""
